#!/bin/sh

userresources=$X11_CONFIG_HOME/Xresources
usermodmap=$X11_CONFIG_HOME/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Awesome Keyboard: Ducky One Mini 2 RGB
setxkbmap us -variant intl

if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

# Nice looking bar
# dwm-bar variables
export SEP1="["
export SEP2="]"
export IDENTIFIER="unicode"
dwmblocks &

# pulseaudio
pulseaudio --start

# Wallpaper
nitrogen --restore &

# Compositor
picom --config .config/picom/picom.conf  &

# Execute DWM
exec dwm
