#!/bin/sh

userresources=$X11_CONFIG_HOME/Xresources
usermodmap=$X11_CONFIG_HOME/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Awesome Keyboard: Ducky One Mini 2 RGB
setxkbmap us -variant intl

if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

# Nice looking bar
# dwm-bar variables
export SEP1="["
export SEP2="]"
export IDENTIFIER="unicode"
dwmblocks &

# pulseaudio
pulseaudio --start

# Home dual monitor setup
if [ -n $(xrandr --listmonitors | grep +DP1 | cut -d' ' -f3) ]; then 
  xrandr --output eDP1 --primary --mode 1920x1080 --output DP1 --mode 1920x1080 --left-of eDP1
fi

# Decrease default backlight for savings
xbacklight -set 75

# Wallpaper
nitrogen --restore &

# Compositor
picom --config .config/picom/picom.conf  &

# Requires nmcli and GTK complient with tray 
# Controls wifi connections
# https://man.archlinux.org/man/nm-applet.1.en
nm-applet &

# Execute DWM
exec dwm
