" Basic vimrc for notetaking.
"
" References: 
" ----------
"
" [1] https://tuckerchapman.com/2020/05/09/vimrc_organization/ 
"
source $HOME/.config/vim/init/xdg.vim 	    " XDG 
source $HOME/.config/vim/init/options.vim 	" Options
source $HOME/.config/vim/init/keymaps.vim 	" Default keymaps
source $HOME/.config/vim/init/plugins.vim 	" Plugins
source $HOME/.config/vim/init/markdown-preview.vim 	" Markdown preview
source $HOME/.config/vim/init/citation.vim 	" Vim citation plugin
source $HOME/.config/vim/init/vimwiki.vim 	" Vimwiki config
source $HOME/.config/vim/init/vimzettel.vim 	" Vim-zettel config
