#!/bin/sh
#
# https://github.com/Mach-OS/Machfiles 
#

# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias grepy='grep -rI --include="*.py"'

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

#
# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Fuzzy finds directories and cd into them
alias fcd='cd "$(find -type d,l | fzf)"'
#
# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# Top process 
# i. eating cpu
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
# ii. eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

