require("user.options")
require("user.keymaps")
require("user.plugins")

require("user.alpha")
require("user.autocommands")
require("user.autopairs")
require("user.bufferline")
require("user.comment")
require("user.nvim-webdev-icons")
require("user.project")
require("user.treesitter")
require("user.cmp")
require "user.dap"
require("user.impatient")
require("user.lualine")
require("user.lsp")
require("user.telescope")
require("user.colorscheme")
require("user.gitsigns")
require("user.indentline")
require("user.nvim-tree")
require("user.toggleterm")
require("user.tmux-navigator")

