#!/bin/sh
#
# https://github.com/Mach-OS/Machfiles 
#

# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias grepy='grep -rI --include="*.py"'

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

#
# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Fuzzy finds directories and cd into them
alias fcd='cd "$(find -type d,l | fzf)"'
#
# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# Top process 
# i. eating cpu
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
# ii. eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# BUGFIX: libreoffice-still dependencies are deprecated
iculib='/home/gsavarela/.local/share/usr/lib'
alias libreoffice-dev='LD_LIBRARY_PATH="${iculib}" /home/gsavarela/Repos/artix/libreoffice/instdir/program/soffice'
alias libreoffice='LD_LIBRARY_PATH="${iculib}" libreoffice'
alias keepassxc='LD_LIBRARY_PATH="${iculib}" keepassxc'
alias keepassxc-cli2='LD_LIBRARY_PATH="${iculib}" keepassxc-cli'
alias android-file-transfer='LD_LIBRARY_PATH=${iculib}" android-file-transfer'
# SUMO TOOLS
alias sumo='LD_LIBRARY_PATH="${iculib}" sumo'
alias sumo-gui='LD_LIBRARY_PATH="${iculib}" sumo-gui'
alias netconvert='LD_LIBRARY_PATH="${iculib}" netconvert'
alias netedit='LD_LIBRARY_PATH="${iculib}" netedit'
