set nocompatible              " be iMproved, required
filetype off                  " required

" set XDG paths
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif


" set the runtime path to include Vundle and initialize
" set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim

" Keep Plugin commands between vundle#begin/end.
call vundle#begin('~/.config/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Colorscheme
Plugin 'morhetz/gruvbox'

"Derivative of powerline but lighter
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" PYTHON plugins
" jedi-vim provides code completion for vim
Plugin 'davidhalter/jedi-vim'

" IDE for python
" python-mode: https://github.com/python-mode/python-mode
" Plugin 'python-mode/python-mode'

" vim-poliglot: offers syntax highlighting 
Plugin 'sheerun/vim-polyglot'

" Integrates Git commands with vim functionalities
Plugin 'tpope/vim-fugitive'


" Allows markdown files preview
Plugin 'iamcco/markdown-preview.nvim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
" Put your non-Plugin stuff after this line
" Colorscheme
set background=dark
colo gruvbox
let g:airline_theme='gruvbox'

set relativenumber
set ruler
syntax enable

let g:python_highlight_all = 1
" TODO: basic test settings
filetype plugin on

"ctags path
"set tags=./tags;

"recursive path lookup
set path+=**
" set path+=$ILURL_HOME/..

"show files and words during search
set wildmenu
set hls

"load views
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

"default calcurse notes format 
autocmd BufRead,BufNewFile /tmp/calcurse*,~/.calcurse/notes/* set filetype=markdown

"tabs behaviour
set expandtab
set tabstop=4
set shiftwidth=4
